#!/usr/bin/env python3
"""Replay verified real LLM/API artifacts through four native TEST validators.

Wallets here are ephemeral transport keys explicitly committed in closed TEST genesis.
No LLM conclusion, reviewer verdict, or calculator result is generated by this adapter.
"""

import argparse
import base64
import hashlib
import json
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
for path in (ROOT, ROOT / "native", ROOT / "native/tools", ROOT / "apps/api"):
    sys.path.insert(0, str(path))
from agora_api.research_export import verify_package
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey, Ed25519PublicKey
from scripts.v03_llm_evaluate import evaluate, verify_tools
from v03_network import NativeNetwork

from tokoin_native.core import address, digest, make_genesis
from tokoin_native.v03_science import PROTOCOL, commitment, genesis_v03, receipt, tree
from tokoin_native.wallet import public_key, sign, transaction


def write(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n")


def file_hash(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def b64(value):
    return base64.urlsafe_b64decode(value + "=" * (-len(value) % 4))


def verify_handoff(case, identities, campaign):
    result = verify_package(case["package"], case["candidate"]["content_hash"])
    case_id = case["experiment"]["id"]
    exported = {obj["object_id"]: obj for obj in case["package"]["objects"]}
    for node in case["nodes"]:
        obj = exported[node["object_id"]]
        if (
            node["canonical_content_hash"] != obj["content_hash"]
            or node["payload"] != obj["canonical_payload"]["payload"]
        ):
            raise ValueError("API node differs from verified candidate object")
        source_agent = campaign["agents"][node["role"]]
        expected_contribution = next(
            c for c in source_agent["contributions"] if c["experiment_id"] == case_id
        )
        expected_tools = [
            t for t in source_agent["tool_artifacts"] if t["request"]["experiment_id"] == case_id
        ]
        payload = node["payload"]
        if (
            payload["contribution"] != expected_contribution
            or payload["tools"] != expected_tools
            or payload["llm_result_hash"] != source_agent["content_hash"]
            or payload["agent_id"] != source_agent["agent_id"]
        ):
            raise ValueError("API contribution differs from original model output")
        if node["author_agent_id"] != identities[node["role"]]["agent_id"]:
            raise ValueError("API author does not match persistent LLM identity")
    if len(case["reviews"]) != 2:
        raise ValueError("two real API reviews required")
    for review in case["reviews"]:
        identity = identities[review["role"]]
        expected = next(
            c
            for c in campaign["agents"][review["role"]]["contributions"]
            if c["experiment_id"] == case_id
        )
        mapped = {
            "APPROVE": "APPROVED",
            "REJECT": "REJECTED",
            "INCONCLUSIVE": "INSUFFICIENT_EVIDENCE",
            "REQUEST_REPLICATION": "REQUIRES_REVISION",
        }
        if (
            review["llm_contribution"] != expected
            or review["payload"]["verdict"] != mapped[expected["verdict"]]
            or any(
                review["payload"][field] != expected["public_conclusion"]
                for field in ("summary", "methodology_findings", "evidence_findings")
            )
        ):
            raise ValueError("Review differs from signed API payload or original model output")
        if (
            review["agora_agent_id"] != identity["agent_id"]
            or review["public_key"] != identity["public_key"]
        ):
            raise ValueError("API reviewer identity mismatch")
        Ed25519PublicKey.from_public_bytes(b64(review["public_key"])).verify(
            b64(review["signature"]), review["commit_hash"].encode()
        )
        body = {
            "assignment_id": review["assignment_id"],
            "validator_id": review["validator_id"],
            "candidate_id": case["candidate"]["candidate_id"],
            "candidate_content_hash": case["candidate"]["content_hash"],
            "candidate_version": case["package"]["candidate"]["canonical_payload"][
                "candidate_version"
            ],
            "review": review["payload"],
        }
        from agora_api.research_export import content_hash

        if content_hash(body, "agora.institutional.validator.review.v1") != review["commit_hash"]:
            raise ValueError("API review reveal does not match signed commitment")
    return result


def run(source, output):
    source, output = source.resolve(), output.resolve()
    if output.exists():
        raise FileExistsError("Use fresh evidence directory")
    report = json.loads((source / "results.json").read_text())
    if report["status"] != "PASS" or len(report["cases"]) != 5:
        raise ValueError("A completed five-case real API campaign is required")
    from scripts.v03_llm_export import export

    verified = export(source)
    report["cases"] = verified["cases"]
    campaign = json.loads((source / "llm/campaign.json").read_text())
    identities = report["identities"]
    if len(identities) < 6:
        raise ValueError("At least six persistent real model actors required")
    tool_count, accuracy = verify_tools(campaign), evaluate(campaign)
    for case in report["cases"].values():
        verify_handoff(case, identities, campaign)
    output.mkdir(parents=True)
    keys = {role: Ed25519PrivateKey.generate() for role in identities}
    infra = Ed25519PrivateKey.generate()
    metadata = {}
    for role, identity in identities.items():
        invocation = json.loads((source / "llm" / role / "round-0/receipt.json").read_text())
        metadata[role] = {
            "agent_id": identity["agent_id"],
            "model": invocation["model_requested"],
            "provider": identity["provider"],
            "passport_hash": digest("tokoin.science.passport.v03", identity),
            "controller_group": "TEST-context-" + role,
        }
    registry = {
        public_key(keys[r]): {
            "institution_id": "TEST-" + r,
            "controller_group": metadata[r]["controller_group"],
            "payout_address": address(public_key(keys[r])),
            "label": "INSTITUTIONAL_VALIDATOR_TEST",
        }
        for r in ("reviewer_a", "reviewer_b")
    }
    commitments = {
        public_key(keys[r]): digest("tokoin.science.identity.v03", m) for r, m in metadata.items()
    }
    mapping = {
        r: {
            "agora_passport": identities[r],
            "monetary_public_key": public_key(keys[r]),
            "metadata": m,
            "control": "EPHEMERAL_TRANSPORT_KEY_SINGLE_OPERATOR_TEST",
        }
        for r, m in metadata.items()
    }
    write(output / "identity-map.json", mapping)
    summary = {
        "schema_version": "AGORA_V03_RUN_V1",
        "run_id": output.name,
        "experiment_id": "V03-02",
        "status": "RUNNING",
        "source_campaign": str(source.relative_to(ROOT)),
        "source_campaign_sha256": file_hash(source / "results.json"),
        "tool_replays": tool_count,
        "scientific_experiments": [],
        "contribution_nodes": [],
        "contribution_edges": [],
        "reward_derivations": [],
        "limitations": [
            "All eight model actors and four validators share one human operator. TEST context groups are not independently owned institutions.",  # noqa: E501
            "Genesis binds the published API passport to an ephemeral transport wallet; no agent private monetary custody or external identity attestation is claimed.",  # noqa: E501
            "API packages and calculator artifacts are verified offline; chain validates commitments, lifecycle and signatures, not scientific truth.",  # noqa: E501
            "Missing-input cases record unexecuted methods explicitly; no result is fabricated.",
            "No real calendar maturity, transferable mainnet funds, or public genesis recognition.",
        ],
    }

    def factory(validators, timestamp):
        return genesis_v03(
            make_genesis(
                "tokoin-test-v03-network",
                registry,
                address(public_key(infra)),
                timestamp,
                validators,
            ),
            commitments,
        )

    try:
        with NativeNetwork(output / "network", genesis_factory=factory) as net:

            def send(role, kind, payload, reject=False):
                state = net.state()
                tx = transaction(
                    keys[role],
                    net.genesis,
                    state["nonces"].get(address(public_key(keys[role])), 0) + 1,
                    kind,
                    payload,
                )
                return net.submit(tx, expect_reject=reject)

            for role, identity in metadata.items():
                send(role, "science_identity", identity)
            for case_id, case in sorted(report["cases"].items()):
                cid, events = case["challenge_id"], []
                nodes = {n["role"]: n for n in case["nodes"]}
                evidence_refs = []
                write(output / "artifacts" / f"{case_id}-api-package.json", case)

                def event(
                    kind,
                    role,
                    artifact,
                    parents=None,
                    *,
                    case_id=case_id,
                    events=events,
                    case=case,
                    cid=cid,
                ):
                    eid = case_id + "-e" + str(len(events))
                    artifact_path = output / "artifacts" / f"{eid}.json"
                    write(artifact_path, artifact)
                    content = {
                        "artifact_sha256": file_hash(artifact_path),
                        "artifact_path": str(artifact_path.relative_to(output)),
                        "agora_candidate_hash": case["candidate"]["content_hash"],
                        "agora_challenge_id": cid,
                    }
                    parent_ids = parents if parents is not None else events[-1:]
                    send(
                        role,
                        "science_event",
                        {
                            "event_id": eid,
                            "challenge_id": cid,
                            "kind": kind,
                            "agent_id": identities[role]["agent_id"],
                            "parents": parent_ids,
                            "content": content,
                            "content_hash": digest("tokoin.science.content.v03", content),
                        },
                    )
                    summary["contribution_nodes"].append(
                        {
                            "node_id": eid,
                            "agent_id": identities[role]["agent_id"],
                            "kind": kind,
                            "content_hash": content["artifact_sha256"],
                            "source_path": str(artifact_path.relative_to(ROOT)),
                        }
                    )
                    summary["contribution_edges"].extend(
                        {"source": parent, "target": eid, "relation": "protocol_predecessor"}
                        for parent in parent_ids
                    )
                    events.append(eid)
                    return eid

                event(
                    "challenge_created",
                    "proposer",
                    {
                        "creation": case.get("creation"),
                        "experiment": case["experiment"],
                        "api_challenge_id": cid,
                    },
                )
                event("hypothesis_registered", "proposer", nodes["proposer"])
                for role in nodes:
                    event("agent_contribution_registered", role, nodes[role])
                event("evidence_committed", "primary_researcher", case["package"])
                primary = next(
                    c
                    for c in campaign["agents"]["primary_researcher"]["contributions"]
                    if c["experiment_id"] == case_id
                )
                tools = [
                    t
                    for t in campaign["agents"]["primary_researcher"]["tool_artifacts"]
                    if t["request"]["experiment_id"] == case_id
                ]
                evidence_refs.append(
                    event(
                        "experiment_registered",
                        "primary_researcher",
                        {
                            "requests": [t["request"] for t in tools],
                            "execution_status": "EXECUTED"
                            if tools
                            else "NOT_EXECUTED_MISSING_INPUT",
                            "public_conclusion": primary["public_conclusion"],
                        },
                    )
                )
                solver = event(
                    "experiment_result_committed",
                    "primary_researcher",
                    {
                        "tool_artifacts": tools,
                        "contribution": primary,
                        "api_node": nodes["primary_researcher"],
                    },
                )
                evidence_refs.append(solver)
                replicas = [
                    t
                    for t in campaign["agents"]["replicator"]["tool_artifacts"]
                    if t["request"]["experiment_id"] == case_id
                ]
                evidence_refs.append(
                    event(
                        "replication_registered",
                        "replicator",
                        {
                            "tool_artifacts": replicas,
                            "api_node": nodes["replicator"],
                            "execution_status": "EXECUTED"
                            if replicas
                            else "NOT_EXECUTED_MISSING_INPUT",
                        },
                    )
                )
                root = tree(net.state(), cid)
                reviews = []
                for review in case["reviews"]:
                    role, contribution = review["role"], review["llm_contribution"]
                    review_file = output / "artifacts" / f"{case_id}-{role}-review.json"
                    write(review_file, review)
                    # Assessment is a public hash-linked model conclusion, not a new judgment.
                    assessment = json.dumps(
                        {
                            "source_sha256": file_hash(review_file),
                            "api_commit_hash": review["commit_hash"],
                            "conclusion": contribution["public_conclusion"],
                        },
                        ensure_ascii=True,
                    )
                    body = {
                        "review_id": case_id + "-" + role,
                        "challenge_id": cid,
                        "reviewer_identity": identities[role]["agent_id"],
                        "institution_identity_if_applicable": "TEST-" + role,
                        "methodology_assessment": assessment,
                        "evidence_assessment": assessment,
                        "replication_assessment": assessment,
                        "verdict": contribution["verdict"],
                        "conflict_of_interest_declaration": {"has_conflict": False},
                        "protocol_version": PROTOCOL,
                        "contribution_tree_root": root,
                        "evidence_refs": evidence_refs,
                    }
                    salt = secrets.token_hex(32)
                    send(
                        role,
                        "science_review_commit",
                        {"challenge_id": cid, "commitment": commitment(body, salt)},
                    )
                    reviews.append((role, body, salt))
                for role, body, salt in reviews:
                    send(
                        role,
                        "science_review_reveal",
                        {
                            "challenge_id": cid,
                            "receipt": receipt(keys[role], body, salt),
                            "salt": salt,
                        },
                    )
                send("primary_researcher", "science_decide", {"challenge_id": cid})
                # The false universal hypothesis has actual counterexample reviews.
                # Those signed conclusions authorize the adapter's explicit TEST objection resolution.  # noqa: E501
                if case_id == "LLM-SCI-002" and all(
                    body["verdict"] == "REJECT" for _, body, _ in reviews
                ):
                    counter = [
                        t
                        for t in campaign["agents"]["critic"]["tool_artifacts"]
                        if t["request"]["experiment_id"] == case_id
                    ]
                    if not counter:
                        raise ValueError(
                            "No real critic counterexample: cannot manufacture objection"
                        )
                    evidence = digest("tokoin.science.counterexample.v03", counter)
                    method = digest("tokoin.science.method.v03", [t["request"] for t in counter])
                    objection_id = case_id + "-objection"
                    send(
                        "critic",
                        "science_objection",
                        {
                            "challenge_id": cid,
                            "objection_id": objection_id,
                            "target_event_id": events[0],
                            "evidence_hash": evidence,
                            "method_hash": method,
                        },
                    )
                    decision = {
                        "chain_id": net.genesis["chain_id"],
                        "genesis_hash": net.state()["genesis_hash"],
                        "challenge_id": cid,
                        "objection_id": objection_id,
                        "outcome": "UPHELD",
                        "evidence_hash": evidence,
                    }
                    send(
                        "critic",
                        "science_resolve",
                        {
                            "challenge_id": cid,
                            "decision": decision,
                            "signatures": {
                                public_key(keys[role]): sign(
                                    keys[role], "tokoin.science.resolve.v03", decision
                                )
                                for role, _, _ in reviews
                            },
                        },
                    )
                send(
                    "primary_researcher",
                    "science_freeze",
                    {"challenge_id": cid, "contribution_tree_root": root},
                )
                rid = case_id + "-review20"
                send(
                    "primary_researcher",
                    "science_settle_review",
                    {"challenge_id": cid, "reward_id": rid},
                )
                state = net.state()
                if state["science"]["research"][cid]["decision"] == "APPROVE":
                    send(
                        "primary_researcher",
                        "science_settle_result",
                        {
                            "challenge_id": cid,
                            "reward_id": case_id + "-result80",
                            "solver_event_id": solver,
                        },
                    )
                send("primary_researcher", "finalize", {"reward_id": rid}, reject=True)
                send(
                    "reviewer_a",
                    "transfer",
                    {"to": address(public_key(keys["proposer"])), "amount": 1},
                    reject=True,
                )
                send(
                    "primary_researcher",
                    "science_settle_review",
                    {"challenge_id": cid, "reward_id": rid + "-replay"},
                    reject=True,
                )
                state = net.state()
                rewards = {
                    k: v
                    for k, v in state["rewards"].items()
                    if v["authorization"]["challenge_id"] == cid
                }
                if any(v["status"] != "LOCKED" for v in rewards.values()) or state["balances"]:
                    raise ValueError("Premature available funds")
                for reward_id, value in rewards.items():
                    summary["reward_derivations"].append(
                        {
                            "experiment_id": case_id,
                            "reward_id": reward_id,
                            "units": value["authorization"]["reward_total"],
                            "pool_kind": value["authorization"]["pool_kind"],
                            "allocations": value["allocations"],
                            "tree_root": root,
                            "locked_until": value["unlock_at"],
                        }
                    )
                ev = str((output / "network/results.json").relative_to(ROOT))
                row = {
                    "experiment_id": case_id,
                    "decision": state["science"]["research"][cid]["decision"],
                    "reward_units": sum(
                        v["authorization"]["reward_total"] for v in rewards.values()
                    ),
                }
                for axis in (
                    "consensus_correctness",
                    "state_machine_correctness",
                    "economic_correctness",
                    "provenance_correctness",
                    "scientific_protocol_correctness",
                ):
                    row[axis] = {
                        "status": "PASS",
                        "evidence": [ev],
                        "reason": "Actual signed API artifact, native inclusion, locked wallet and negative transaction checks; final network replay required.",  # noqa: E501
                    }
                row["scientific_result_accuracy"] = {
                    "status": accuracy[case_id]["scientific_result_accuracy"],
                    "evidence": [str((source / "llm/campaign.json").relative_to(ROOT))],
                    "reason": "Independent fixed benchmark oracle, no model verdict rewrite.",
                }
                summary["scientific_experiments"].append(row)
                write(output / "wallet-state.json", state)
                write(output / "science-results.json", summary)
            net.compare()
        network = json.loads((output / "network/results.json").read_text())
        if network["status"] != "PASS":
            raise ValueError("Four-node replay or consensus evidence failed")
        summary["status"] = "PASS"
        summary["consensus_results"] = network["consensus_results"]
        summary["apphash_consistency"] = network["apphash_consistency"]
    except Exception as exc:
        summary["status"] = "FAIL"
        summary["failure"] = {"type": type(exc).__name__, "message": str(exc)}
        raise
    finally:
        write(output / "science-results.json", summary)
        write(
            output / "artifact-index.json",
            {
                str(p.relative_to(output)): file_hash(p)
                for p in sorted((output / "artifacts").glob("*.json"))
            },
        )
    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    print(json.dumps(run(args.source, args.output), indent=2))
