#!/usr/bin/env python3
"""Single source of truth for the counts AGORA quotes about itself.

Every number the public docs cite about the size of this repository — MCP
tools, ADRs, DB migrations, tests — is derived here from the working tree,
never typed by hand. ``METRICS.json`` at the repo root is the machine-readable
output; markdown files opt in to a rendered one-line summary.

Usage
-----
    python scripts/collect_metrics.py            # regenerate METRICS.json + docs
    python scripts/collect_metrics.py --check    # verify only, writes nothing (CI)

Adding the block to another markdown file
-----------------------------------------
Paste these two lines where the numbers should appear, then re-run the script
without ``--check``. Everything between the markers is regenerated::

    <!-- AGORA:METRICS:START -->
    <!-- AGORA:METRICS:END -->

Any ``.md`` file in the repository is discovered automatically (README.md,
docs/paper/*.md, …), so onboarding a new document needs no code change here.
Injection is idempotent: running the script twice produces identical bytes.

Drift policy
------------
``--check`` compares the counts only, never ``generated_from_commit``: HEAD
moves with every commit and that is not drift. A count that cannot be computed
in the current environment (pytest missing, native extras not installed) is
carried over from METRICS.json instead of being guessed or nulled — a missing
tool must never silently rewrite a published number, nor fail the build by
itself.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

START_MARKER = "<!-- AGORA:METRICS:START -->"
END_MARKER = "<!-- AGORA:METRICS:END -->"

ATTRIBUTION = "*Counts generated by `scripts/collect_metrics.py`; CI fails if they drift.*"

METRICS_FILENAME = "METRICS.json"

MCP_SERVER_PATH = Path("bridge/agora_bridge/mcp_server.py")
ADR_DIR = Path("docs/adr")
MIGRATIONS_DIR = Path("apps/api/alembic/versions")

TOOL_DECORATOR = re.compile(r"@server\.tool\b")
ADR_NUMBER = re.compile(r"ADR-(\d+)")
COLLECTED = re.compile(r"(\d+) tests? collected")

# Directories that never contribute metrics or host injected blocks.
SKIP_DIRS = frozenset(
    {".git", ".venv", "node_modules", "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache"}
)

# Counts that are derived by importing/collecting tests rather than by reading
# files. These may be unavailable in a stripped environment; see "Drift policy".
OPTIONAL_COUNTS = ("python_tests", "native_tests")


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def count_mcp_tools(root: Path) -> int:
    """Count ``@server.tool`` decorators registering MCP tools on the Bridge."""
    source = root / MCP_SERVER_PATH
    if not source.is_file():
        return 0
    return len(TOOL_DECORATOR.findall(source.read_text(encoding="utf-8")))


def adr_files(root: Path) -> list[Path]:
    return sorted((root / ADR_DIR).glob("ADR-*.md"))


def adr_range(files: list[Path]) -> dict[str, str] | None:
    """Lowest and highest ADR identifiers.

    The file count and the range can legitimately disagree: numbers may be
    skipped, and two ADRs occasionally share a number. The range describes the
    numbering, the count describes the files.
    """
    numbers = [int(match.group(1)) for path in files if (match := ADR_NUMBER.search(path.name))]
    if not numbers:
        return None
    return {"lowest": f"ADR-{min(numbers):04d}", "highest": f"ADR-{max(numbers):04d}"}


def migration_files(root: Path) -> list[Path]:
    """Alembic revision modules, excluding ``__pycache__`` and package files."""
    directory = root / MIGRATIONS_DIR
    if not directory.is_dir():
        return []
    return sorted(
        path
        for path in directory.glob("*.py")
        if path.is_file() and not path.name.startswith("__")
    )


def _python_executable(root: Path) -> str:
    """Prefer the repo virtualenv so the script works under a bare interpreter."""
    venv_python = root / ".venv" / "bin" / "python"
    if venv_python.is_file():
        return str(venv_python)
    return sys.executable


def collect_test_count(root: Path, pytest_args: list[str]) -> int | None:
    """Total tests pytest collects, or ``None`` when collection is unavailable.

    Never falls back to a guess: an unparseable or failing run yields ``None``
    so the caller can carry the previously published number forward.
    """
    command = [_python_executable(root), "-m", "pytest", "--collect-only", "-q", *pytest_args]
    try:
        completed = subprocess.run(
            command,
            cwd=root,
            capture_output=True,
            text=True,
            timeout=600,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if completed.returncode != 0:
        return None
    matches = COLLECTED.findall(completed.stdout)
    if not matches:
        return None
    return int(matches[-1])


def git_commit(root: Path) -> str:
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return "unknown"
    if completed.returncode != 0:
        return "unknown"
    return completed.stdout.strip() or "unknown"


def build_metrics(root: Path, *, collect_tests: bool = True) -> dict[str, object]:
    """Derive every published count from the working tree."""
    adrs = adr_files(root)
    migrations = migration_files(root)

    counts: dict[str, int | None] = {
        "mcp_tools": count_mcp_tools(root),
        "adrs": len(adrs),
        "migrations": len(migrations),
    }
    if collect_tests:
        counts["python_tests"] = collect_test_count(root, ["tests"])
        counts["native_tests"] = collect_test_count(
            root, ["-c", "native/pyproject.toml", "--confcutdir=native", "native/tests"]
        )
    else:
        counts["python_tests"] = None
        counts["native_tests"] = None

    return {
        "generated_from_commit": git_commit(root),
        "counts": counts,
        "latest_migration": migrations[-1].stem if migrations else None,
        "adr_range": adr_range(adrs),
    }


def merge_optional_counts(
    fresh: dict[str, object], previous: dict[str, object] | None
) -> dict[str, object]:
    """Carry forward optional counts that could not be computed right now."""
    if previous is None:
        return fresh
    fresh_counts = dict(fresh["counts"])  # type: ignore[arg-type]
    previous_counts = previous.get("counts")
    if not isinstance(previous_counts, dict):
        return fresh
    for key in OPTIONAL_COUNTS:
        if fresh_counts.get(key) is None and previous_counts.get(key) is not None:
            fresh_counts[key] = previous_counts[key]
    merged = dict(fresh)
    merged["counts"] = fresh_counts
    return merged


def render_block(metrics: dict[str, object]) -> str:
    """Render the markdown shown between the markers."""
    counts = metrics["counts"]
    assert isinstance(counts, dict)
    segments: list[str] = []

    if counts.get("mcp_tools"):
        segments.append(f"**{counts['mcp_tools']}** MCP tools")

    if counts.get("adrs"):
        adrs = f"**{counts['adrs']}** ADRs"
        span = metrics.get("adr_range")
        if isinstance(span, dict):
            adrs += f" ({span['lowest']}–{span['highest']})"
        segments.append(adrs)

    if counts.get("migrations"):
        migrations = f"**{counts['migrations']}** migrations"
        latest = metrics.get("latest_migration")
        if latest:
            migrations += f" (latest `{latest}`)"
        segments.append(migrations)

    if counts.get("python_tests"):
        segments.append(f"**{counts['python_tests']}** Python tests")

    if counts.get("native_tests"):
        segments.append(f"**{counts['native_tests']}** native TOKOIN tests")

    return " · ".join(segments) + "\n\n" + ATTRIBUTION


def inject(text: str, block: str) -> str:
    """Replace every marker-delimited region with ``block``.

    Idempotent by construction: the markers are preserved and only the region
    between them is rewritten, so re-running on the output is a no-op.
    """
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    replacement = f"{START_MARKER}\n{block}\n{END_MARKER}"
    return pattern.sub(lambda _: replacement, text)


def marker_files(root: Path) -> list[Path]:
    """Markdown files that opted into the injected block, in stable order."""
    found: list[Path] = []
    for path in sorted(root.rglob("*.md")):
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if START_MARKER in text and END_MARKER in text:
            found.append(path)
    return found


def serialize(metrics: dict[str, object]) -> str:
    return json.dumps(metrics, indent=2, sort_keys=True) + "\n"


def load_metrics(path: Path) -> dict[str, object] | None:
    if not path.is_file():
        return None
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return loaded if isinstance(loaded, dict) else None


def write(root: Path, metrics: dict[str, object]) -> list[Path]:
    """Write METRICS.json and refresh every injected block. Returns changed files."""
    changed: list[Path] = []

    metrics_path = root / METRICS_FILENAME
    payload = serialize(metrics)
    if not metrics_path.is_file() or metrics_path.read_text(encoding="utf-8") != payload:
        metrics_path.write_text(payload, encoding="utf-8")
        changed.append(metrics_path)

    block = render_block(metrics)
    for path in marker_files(root):
        original = path.read_text(encoding="utf-8")
        updated = inject(original, block)
        if updated != original:
            path.write_text(updated, encoding="utf-8")
            changed.append(path)

    return changed


def check(root: Path, metrics: dict[str, object]) -> list[str]:
    """Report drift between the tree and what is published. Writes nothing."""
    problems: list[str] = []

    metrics_path = root / METRICS_FILENAME
    published = load_metrics(metrics_path)
    if published is None:
        problems.append(f"{METRICS_FILENAME} is missing or unreadable")
    else:
        fresh_counts = metrics["counts"]
        published_counts = published.get("counts")
        assert isinstance(fresh_counts, dict)
        if not isinstance(published_counts, dict):
            problems.append(f"{METRICS_FILENAME} has no 'counts' object")
        else:
            for key, value in fresh_counts.items():
                if value is None:
                    # Not computable here; carried forward, so nothing to compare.
                    continue
                if published_counts.get(key) != value:
                    problems.append(
                        f"{METRICS_FILENAME}: {key} says {published_counts.get(key)!r}, "
                        f"tree says {value!r}"
                    )
        for key in ("latest_migration", "adr_range"):
            if metrics[key] is not None and published.get(key) != metrics[key]:
                problems.append(
                    f"{METRICS_FILENAME}: {key} says {published.get(key)!r}, "
                    f"tree says {metrics[key]!r}"
                )

    block = render_block(metrics)
    for path in marker_files(root):
        original = path.read_text(encoding="utf-8")
        if inject(original, block) != original:
            problems.append(f"{path.relative_to(root)}: injected metrics block is stale")

    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify METRICS.json and injected blocks match the tree; write nothing",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="repository root (defaults to the checkout containing this script)",
    )
    parser.add_argument(
        "--no-collect-tests",
        action="store_true",
        help="skip pytest collection; test counts are carried over from METRICS.json",
    )
    args = parser.parse_args(argv)

    root = (args.root or repo_root()).resolve()
    metrics = build_metrics(root, collect_tests=not args.no_collect_tests)
    metrics = merge_optional_counts(metrics, load_metrics(root / METRICS_FILENAME))

    if args.check:
        problems = check(root, metrics)
        if problems:
            print("Metrics drift detected:", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            print(
                "\nRun `python scripts/collect_metrics.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("Metrics are in sync with the tree.")
        return 0

    changed = write(root, metrics)
    if changed:
        for path in changed:
            print(f"updated {path.relative_to(root)}")
    else:
        print("Metrics already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
